"""Extract the text of a .docx as a list of paragraph strings, the way a reader sees it.

python-docx's `paragraph.text` is only the typed text. Two things a reader sees are
not in it, and both are common in Word quizzes:

* Automatic list numbering. If the options of a question are an auto-lettered list
  (A. B. C.), the letters are generated by Word and are NOT in the text, so the
  parser never sees "A)" and the options also look like new questions. The labels
  are rebuilt here from the document's numbering definitions.
* Tables. `document.paragraphs` skips them entirely, silently dropping their text.

Only the label formats the quiz parser can use are produced: decimal ("1.") and
upper/lower letters. Letters are always written "A)" / "a)" whatever punctuation Word
shows ("A.", "(a)", ...), because "A)" is the option form the parser documents and
routes on; a bare "A." is not recognised as a multiple-choice option. Bullets, roman
numerals and anything else are left as plain text, because a made-up label would be
worse than none.
"""
from docx.oxml.ns import qn

_SUPPORTED_FORMATS = {"decimal", "upperLetter", "lowerLetter"}
_MAX_LEVELS = 9


def _val(element, tag, default=None):
    child = element.find(qn(tag)) if element is not None else None
    return child.get(qn("w:val")) if child is not None else default


def _letters(n, upper):
    """1 -> A, 26 -> Z, 27 -> AA, ... (Word's letter numbering)."""
    out = ""
    while n > 0:
        n, rem = divmod(n - 1, 26)
        out = chr(ord("A") + rem) + out
    return out if upper else out.lower()


def _format_counter(n, fmt):
    if fmt == "decimal":
        return str(n)
    if fmt == "upperLetter":
        return _letters(n, True)
    if fmt == "lowerLetter":
        return _letters(n, False)
    return None


class _Numbering:
    """Resolves Word list numbering into text labels, tracking counters in document order."""

    def __init__(self, document):
        self.nums = {}       # numId -> (abstractNumId, {ilvl: startOverride})
        self.abstracts = {}  # abstractNumId -> {ilvl: (numFmt, lvlText, start)}
        self.counters = {}   # abstractNumId -> {ilvl: current count}
        self.seen_nums = set()

        try:
            root = document.part.numbering_part.element
        except Exception:  # no numbering part: nothing to resolve
            return

        for abstract in root.findall(qn("w:abstractNum")):
            levels = {}
            for lvl in abstract.findall(qn("w:lvl")):
                try:
                    ilvl = int(lvl.get(qn("w:ilvl")))
                    start = int(_val(lvl, "w:start", "1"))
                except (TypeError, ValueError):
                    continue
                levels[ilvl] = (_val(lvl, "w:numFmt", "decimal"), _val(lvl, "w:lvlText", ""), start)
            self.abstracts[abstract.get(qn("w:abstractNumId"))] = levels

        for num in root.findall(qn("w:num")):
            overrides = {}
            for override in num.findall(qn("w:lvlOverride")):
                start_override = override.find(qn("w:startOverride"))
                if start_override is not None:
                    try:
                        overrides[int(override.get(qn("w:ilvl")))] = int(start_override.get(qn("w:val")))
                    except (TypeError, ValueError):
                        pass
            self.nums[num.get(qn("w:numId"))] = (_val(num, "w:abstractNumId"), overrides)

    @staticmethod
    def _numpr_for(paragraph):
        """(numId, ilvl) from the paragraph itself or, failing that, its style chain."""
        numpr = paragraph._p.pPr.numPr if paragraph._p.pPr is not None else None
        num_id = numpr.numId.val if numpr is not None and numpr.numId is not None else None
        ilvl = numpr.ilvl.val if numpr is not None and numpr.ilvl is not None else None

        style = paragraph.style
        guard = 0
        while (num_id is None or ilvl is None) and style is not None and guard < 10:
            style_pr = style.element.pPr
            style_numpr = style_pr.numPr if style_pr is not None else None
            if style_numpr is not None:
                if num_id is None and style_numpr.numId is not None:
                    num_id = style_numpr.numId.val
                if ilvl is None and style_numpr.ilvl is not None:
                    ilvl = style_numpr.ilvl.val
            style = style.base_style
            guard += 1

        return (None if num_id is None else str(num_id)), (0 if ilvl is None else int(ilvl))

    def label(self, paragraph):
        """The visible list label for `paragraph` ("A.", "1)", ...) or None if it has none we can use."""
        num_id, ilvl = self._numpr_for(paragraph)
        if num_id is None or num_id == "0" or num_id not in self.nums:
            return None  # not a list item (numId 0 explicitly removes numbering)

        abstract_id, overrides = self.nums[num_id]
        levels = self.abstracts.get(abstract_id)
        if not levels or ilvl not in levels or ilvl >= _MAX_LEVELS:
            return None

        # Advance the counter for this item even if we end up unable to show a label,
        # so later items in the same list keep the right numbers.
        state = self.counters.setdefault(abstract_id, {})
        if num_id not in self.seen_nums:
            # First use of this list instance: "restart numbering at N" lives here.
            self.seen_nums.add(num_id)
            for lvl, start in overrides.items():
                state[lvl] = start - 1
        current = state.get(ilvl)
        state[ilvl] = levels[ilvl][2] if current is None else current + 1
        for deeper in [lvl for lvl in state if lvl > ilvl]:
            del state[deeper]

        fmt, lvl_text, _start = levels[ilvl]
        if fmt not in _SUPPORTED_FORMATS or not lvl_text:
            return None  # bullets, roman numerals, ...: leave as plain text

        text = lvl_text
        for level in range(ilvl + 1):
            placeholder = f"%{level + 1}"
            if placeholder not in text:
                continue
            level_fmt, _, level_start = levels.get(level, ("decimal", "", 1))
            rendered = _format_counter(state.get(level, level_start), level_fmt)
            if rendered is None:
                return None
            text = text.replace(placeholder, rendered)
        if "%" in text:  # references a level we couldn't render
            return None

        text = text.strip()
        if fmt in ("upperLetter", "lowerLetter"):
            return text.strip("().") + ")"   # "A." / "(a)" / "A" -> "A)" / "a)" / "A)"
        if text.startswith("(") and text.endswith(")"):
            text = text[1:-1] + ")"          # "(1)" -> "1)": the parser reads "1)" not "(1)"
        elif not text.endswith((".", ")")):
            text += "."
        return text


def _paragraph_text(paragraph, numbering):
    label = numbering.label(paragraph)
    text = paragraph.text
    if label and text.strip():
        return f"{label} {text.strip()}"
    return text


def extract_docx_paragraphs(document):
    """All paragraph strings in reading order: body paragraphs and table cell paragraphs."""
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    numbering = _Numbering(document)
    out = []

    def walk(container, parent):
        for child in container.iterchildren():
            if child.tag == qn("w:p"):
                out.append(_paragraph_text(Paragraph(child, parent), numbering))
            elif child.tag == qn("w:tbl"):
                table = Table(child, parent)
                for row in table.rows:
                    seen_cells = set()
                    for cell in row.cells:
                        # merged cells repeat the same underlying cell; read each once
                        if id(cell._tc) in seen_cells:
                            continue
                        seen_cells.add(id(cell._tc))
                        walk(cell._tc, cell)

    walk(document.element.body, document)
    return out
